version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom_airflow_with_papermill:latest
    container_name: airflow
    environment:
      - MONGODB_URI=mongodb+srv://bulanmurela:Bulanmurela1144@rekdat.hn7zp.mongodb.net/
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: airflow standalone
